on: [push]
jobs:
  Main-action-CD:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "${{ github.ref }} on ${{ github.repository }}..."
      - name: Log in to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run the Docker build job
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rudovc/private:arachnobot
      - run: echo "This job's status is ${{ job.status }}."
